wavsep:
  image: wavsepunina:latest
  container_name: wavsep
  ports:
    - "127.0.0.1:8080:8080"
  links:
    - wavsepdb

#wavsepdb:
# image: mysql/mysql-server:8.0.22-1.1.18-amd64
# environment:
#    - MYSQL_ROOT_PASSWORD=wavsep

wavsepdb:
    image: 'mysql/mysql-server:8.0.22-1.1.18-amd64'
    container_name: wavsepdb
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'wavsep'
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
