wavsep:
   container_name: wavsep
   image: wavsepunina:latest
   ports:
    - "127.0.0.1:8080:8080"
   links:
    - wavsepdb

wavsepdb:
  container_name: wavsepdb
  image: mysql/mysql-server:8.0.22-1.1.18-amd64
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "wavsep"
    MYSQL_ROOT_HOST: "%"